try{
    let a=5;
let sum=a+b;
console.log(sum);
}
catch(error){
    console.log(error.message);  
}
finally{
    console.log("hello");
}

